Traceback (most recent call last):
  File "C:\Users\mtint\anaconda3\lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\mtint\anaconda3\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\mtint\anaconda3\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\mtint\anaconda3\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\mtint\anaconda3\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\mtint\anaconda3\lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "C:\Users\mtint\anaconda3\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\mtint\anaconda3\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
#importando la data del github
shp_dpt= gpd.read_file(r'../../_data/INEI_LIMITE_DEPARTAMENTAL/INEI_LIMITE_DEPARTAMENTAL.shp')
shp_dpt
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mCPLE_OpenFailedError[0m                      Traceback (most recent call last)
[1;32mfiona\ogrext.pyx[0m in [0;36mfiona.ogrext.gdal_open_vector[1;34m()[0m

[1;32mfiona\_err.pyx[0m in [0;36mfiona._err.exc_wrap_pointer[1;34m()[0m

[1;31mCPLE_OpenFailedError[0m: ../../_data/INEI_LIMITE_DEPARTAMENTAL/INEI_LIMITE_DEPARTAMENTAL.shp: No such file or directory

During handling of the above exception, another exception occurred:

[1;31mDriverError[0m                               Traceback (most recent call last)
[1;32m~\AppData\Local\Temp\ipykernel_16236\3795121322.py[0m in [0;36m<module>[1;34m[0m
[0;32m      1[0m [1;31m#importando la data del github[0m[1;33m[0m[1;33m[0m[0m
[1;32m----> 2[1;33m [0mshp_dpt[0m[1;33m=[0m [0mgpd[0m[1;33m.[0m[0mread_file[0m[1;33m([0m[1;34mr'../../_data/INEI_LIMITE_DEPARTAMENTAL/INEI_LIMITE_DEPARTAMENTAL.shp'[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m      3[0m [0mshp_dpt[0m[1;33m[0m[1;33m[0m[0m

[1;32m~\anaconda3\lib\site-packages\geopandas\io\file.py[0m in [0;36m_read_file[1;34m(filename, bbox, mask, rows, engine, **kwargs)[0m
[0;32m    257[0m [1;33m[0m[0m
[0;32m    258[0m     [1;32mif[0m [0mengine[0m [1;33m==[0m [1;34m"fiona"[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[1;32m--> 259[1;33m         return _read_file_fiona(
[0m[0;32m    260[0m             [0mpath_or_bytes[0m[1;33m,[0m [0mfrom_bytes[0m[1;33m,[0m [0mbbox[0m[1;33m=[0m[0mbbox[0m[1;33m,[0m [0mmask[0m[1;33m=[0m[0mmask[0m[1;33m,[0m [0mrows[0m[1;33m=[0m[0mrows[0m[1;33m,[0m [1;33m**[0m[0mkwargs[0m[1;33m[0m[1;33m[0m[0m
[0;32m    261[0m         )

[1;32m~\anaconda3\lib\site-packages\geopandas\io\file.py[0m in [0;36m_read_file_fiona[1;34m(path_or_bytes, from_bytes, bbox, mask, rows, where, **kwargs)[0m
[0;32m    301[0m [1;33m[0m[0m
[0;32m    302[0m     [1;32mwith[0m [0mfiona_env[0m[1;33m([0m[1;33m)[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[1;32m--> 303[1;33m         [1;32mwith[0m [0mreader[0m[1;33m([0m[0mpath_or_bytes[0m[1;33m,[0m [1;33m**[0m[0mkwargs[0m[1;33m)[0m [1;32mas[0m [0mfeatures[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m    304[0m             [0mcrs[0m [1;33m=[0m [0mfeatures[0m[1;33m.[0m[0mcrs_wkt[0m[1;33m[0m[1;33m[0m[0m
[0;32m    305[0m             [1;31m# attempt to get EPSG code[0m[1;33m[0m[1;33m[0m[0m

[1;32m~\anaconda3\lib\site-packages\fiona\env.py[0m in [0;36mwrapper[1;34m(*args, **kwds)[0m
[0;32m    455[0m [1;33m[0m[0m
[0;32m    456[0m         [1;32mwith[0m [0menv_ctor[0m[1;33m([0m[0msession[0m[1;33m=[0m[0msession[0m[1;33m)[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[1;32m--> 457[1;33m             [1;32mreturn[0m [0mf[0m[1;33m([0m[1;33m*[0m[0margs[0m[1;33m,[0m [1;33m**[0m[0mkwds[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m    458[0m [1;33m[0m[0m
[0;32m    459[0m     [1;32mreturn[0m [0mwrapper[0m[1;33m[0m[1;33m[0m[0m

[1;32m~\anaconda3\lib\site-packages\fiona\__init__.py[0m in [0;36mopen[1;34m(fp, mode, driver, schema, crs, encoding, layer, vfs, enabled_drivers, crs_wkt, allow_unsupported_drivers, **kwargs)[0m
[0;32m    363[0m [1;33m[0m[0m
[0;32m    364[0m         [1;32mif[0m [0mmode[0m [1;32min[0m [1;33m([0m[1;34m"a"[0m[1;33m,[0m [1;34m"r"[0m[1;33m)[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[1;32m--> 365[1;33m             colxn = Collection(
[0m[0;32m    366[0m                 [0mpath[0m[1;33m,[0m[1;33m[0m[1;33m[0m[0m
[0;32m    367[0m                 [0mmode[0m[1;33m,[0m[1;33m[0m[1;33m[0m[0m

[1;32m~\anaconda3\lib\site-packages\fiona\collection.py[0m in [0;36m__init__[1;34m(self, path, mode, driver, schema, crs, encoding, layer, vsi, archive, enabled_drivers, crs_wkt, ignore_fields, ignore_geometry, include_fields, wkt_version, allow_unsupported_drivers, **kwargs)[0m
[0;32m    232[0m             [1;32mif[0m [0mself[0m[1;33m.[0m[0mmode[0m [1;33m==[0m [1;34m"r"[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[0;32m    233[0m                 [0mself[0m[1;33m.[0m[0msession[0m [1;33m=[0m [0mSession[0m[1;33m([0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[1;32m--> 234[1;33m                 [0mself[0m[1;33m.[0m[0msession[0m[1;33m.[0m[0mstart[0m[1;33m([0m[0mself[0m[1;33m,[0m [1;33m**[0m[0mkwargs[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m    235[0m             [1;32melif[0m [0mself[0m[1;33m.[0m[0mmode[0m [1;32min[0m [1;33m([0m[1;34m"a"[0m[1;33m,[0m [1;34m"w"[0m[1;33m)[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[0;32m    236[0m                 [0mself[0m[1;33m.[0m[0msession[0m [1;33m=[0m [0mWritingSession[0m[1;33m([0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m

[1;32mfiona\ogrext.pyx[0m in [0;36mfiona.ogrext.Session.start[1;34m()[0m

[1;32mfiona\ogrext.pyx[0m in [0;36mfiona.ogrext.gdal_open_vector[1;34m()[0m

[1;31mDriverError[0m: ../../_data/INEI_LIMITE_DEPARTAMENTAL/INEI_LIMITE_DEPARTAMENTAL.shp: No such file or directory
DriverError: ../../_data/INEI_LIMITE_DEPARTAMENTAL/INEI_LIMITE_DEPARTAMENTAL.shp: No such file or directory

